version: "3.18"

services:
  db:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_NAME: ${NAME_DB}

  api:
    container_name: api
    build:
      context: .
    tty: false
    volumes:
      - .:/code
    restart: on-failure
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "python manage.py migrate --noinput & python manage.py runserver 0.0.0.0:8000"
